@startuml
skinparam svgDimensionStyle false

title Verifiable Health Links


participant "Trust Anchor" as TA
participant "VHL Holder" as Consume
participant "VHL Receiver" as Request
participant "VHL Sharer" as Sharer

autonumber "<b>00:</b>"


loop routine synchronization 
  Consume -> TA : retrieves and caches all public keys\nfor VHL verification
end
destroy TA

Request -> Create1  : request VHL enclosing health document\nwith selective disclosure,\ntime limits and passcode
Create1 -> Request : issue and return VHL

Consume -> Respond : retrieve VHLink Manifest [optional]
Respond -> Consume : return VHLink Manifest

Consume -> Respond : retrieve VHLink Clinical Data
Respond -> Consume : return VHLink Clinical Data




@enduml
