@startuml
title VHL Trust Actor Diagram

top to bottom direction
skinparam nodesep 75

agent "Trust Anchor" as TA
agent "VHL Sharer" as VHLS
agent "VHL Receiver" as VHLR

TA -- VHLS  : -"Publish PKI Material\nRetrieve PKI Material"
TA -- VHLR : "Publish PKI Material\nRetrieve PKI Material"
@enduml
