

@startuml
top to bottom direction
skinparam nodesep 75

title VHL Utilization Actor Diagram


agent "Holder" as H
agent "VHL Sharer" as VHLS
agent "VHL Receiver" as VHLR


url of H is [[ActorDefinition-VHLHolder.html]]
url of VHLR is [[ActorDefinition-VHLReceiver.html]]
url of VHLS is [[ActorDefinition-VHLSharer.html]]

H -- VHLS : _"Generate VHL"
H -- VHLR : "Provide VHL"

VHLS -r- VHLR : _"Establish Secure Connection\nRequest Document\nRequest Documents"

@enduml
