
@startuml

top to bottom direction
skinparam nodesep 75

title VHL Trust Actor Diagram

agent "Holder" as H
agent "VHL Sharer" as VHLS
agent "VHL Receiver" as VHLR

H -- VHLS : _"Generate VHL"
H -- VHLR : "Provide VHL"
VHLS -r- VHLR : "Request Document(s)"                                                                                                          
@enduml  
